apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - bootstrap.yaml
  - ippool.yaml
  - secrets/
patches:
  - target:
      kind: Application
      name: projects
    path: ../../../common/patches/argocd-app-settings.yaml
  - target:
      kind: Application
      name: bootstrap
    path: ../../../common/patches/argocd-app-settings.yaml
