apiVersion: v1
kind: Namespace
metadata:
  name: observability-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: proxmox-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: teleport-kube-agent
