apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:

  - ../../apps/bundles/vcluster-r1/

patches:
  - target:
      kind: Application
      name: teleport-kube-agent
    path: patches/teleport-app-configs.yaml
  - target:
      kind: Application
      name: teleport-kube-agent
    path: patches/destination.yaml
  - target:
      kind: Application
      name: metrics-server
    path: patches/destination.yaml