apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../operators/security/teleport-kube-agent
  - ../../../operators/observability/metrics-server

patches:
- target:
    kind: Application
    name: teleport-kube-agent
  path: patches/teleport-app-configs.yaml
- target:
    kind: Application
    name: teleport-kube-agent
  path: patches/destination.yaml