apiVersion: v1
data:
    config.yaml: ENC[AES256_GCM,data:PX30Kg8tUJsciOPAIF/9Btq4tNyFwCwq3+aWJxHbQmDfiVDrhE/OWKKLtgbCnjQTdJ5L918AvN+fbybtJbV2aUcA+QLoHR9onev9o7H9oronzIAF8sY8QvV9yk4pROpqnKtMdOGVE+rAI7KwxMOOnoUWBya9UUDdMSxmvYyhhW1TAjVGFvHwgJG8IA3KUtdTJAWShYn36ToxPQgQwXyIpmvY3wc+iuRK816sQSD2xwhI2BGu14xzW6ZKH8qWljrX9gZyDrb3rt08Z2wOtaRsp1TFa2IR9M4eEPXLZVZsBNxps4bDclrT+w2ZcNG1gcvIqM7wYOL/MI79TUL3Y0NUHpSZmvNDMJXKkqE0hdBhGXHc9i9MBETPOMYZfUf45PprXKZ7OmUwVwCga3dVgF9EGoH2h+ZQlyCxx8cHXFUdLo8qyHvsEX3ZM/uGjGPthzSpfJMR9sByeq2gS9T8I4SPzAH46Nfy3Z6kZdTub156RAcepw9qAX7Dwe1IyRMfJNj+QhxHGmP6UGKbO33BV3J6zjtJo9pzyYPRMllOq7y5DbKWBFUtRFd3tU1qApRPDxGHA54WicPzdVHWpq5rWhNhtLlDTO/fJBAeoA5tDy+GmG3QEczXmkmjqdDETmUYgzWvZCevihwYUllCiyuz6GJUGkdwxB0EY4GWqQCw1iQwpS0=,iv:P8lXj/6pOpKDxRanxydeRhezLhh2b7iahH4lupwnkfo=,tag:Wbw6bjPsKhVKgH6syXCB3w==,type:str]
kind: Secret
metadata:
    name: proxmox-csi-plugin
    namespace: proxmox-system
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-02-08T21:00:37Z"
    mac: ENC[AES256_GCM,data:POnB6g7fp36E1lrTaL9jYSW0VY+fap9H01+bBPe3kYoGuG83YWWyGe81wxw+VtJIaDkp/koFLyliUjA/txL1h2xUetLYmxMYms2Wgu/YmN8iM3nLjnCCZYAVt/LR5LGzwlkrUQLCAvAsTH1BK7zPPmLQnwvFxhftqBOOjRAWf38=,iv:wMcLZWW1sRBGaY9JuhfogdFxrMNxVOrfJxr9MaYuimI=,tag:41LPzuLzl4S29qzzSQLV5A==,type:str]
    pgp:
        - created_at: "2026-02-08T21:00:37Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwFcjQZ1ckKcARAA1Lxcbo0Dsb9dR0WJtUoQUCBnWepD47LgY2fs85pvBY27
            o5gUYcpRoPBQvgsyvT+GvUpT+9kDxVwaOKE86AKjFiTQLgVp+3Sj2TD/G5q9sGE6
            QKv6N6nF9NfwD1pD/eO38pUkNSEslVXg8t21LSQ/+YnhO3all/oMX1vwY76tPidM
            Af4+KoY2G7QkTUrIjBgTl6NIvbEJqcEy7C79jxzpIs3kjoqXdpGAQi9OOot6zkj2
            lez57zrXZLRq3uvK2qF97/YeatcSDOxPTwEHk/d5xPF55+G19m5Yx1oSP5pC4ovB
            7YcNZl9ag1/dOJc1QoY+0unGPSomzQrUGpdGHrgNpbew/96b1mZVgyUPv7J90+x1
            vEKk0AH/YJuLBwFERi/QMA++XBPmm6s+TrZ7JGXKogHcfWb4W9EEOYcO6GyGrT8Z
            m0qcQTiG0xX6s9ZiQFgcKnQPrCLXN1e9ln8zjPV4s5MAElKoT+AoS86Pt3+mD4fp
            tN8DYOydbIJEPD6dNSfhasC9o4Ce4KG4LB4Y6Y38/Wn7tpbVx9XBpufvOHFXC4HU
            K3rLEhVPv2ke/svO30u343V+AK/+TNLbuEukcwvB/M62hEJSeNOOVum9tCJPoerP
            VyNkvYjd98djMuI0hpMu/TT9wiJT3J88L4y+Xt6dL7o1ibPFjLoFcharr6VhqWbU
            ZgEJAhDP9L9alNIsed0tyw/VLJMCHdI2zUrQ6KrCiPaqQd/gjzboILka5agwK5t/
            96fVyqFf4TTBsEdcXOuYkmOxCj6MLOUYq7weSosN2oaSOVO4HICCnj1fTxOFyypj
            qclOU+6s+g==
            =U6MB
            -----END PGP MESSAGE-----
          fp: 4C460A5D1A91A52F3E204754CA746D9D4345890B
    encrypted_regex: ^(data|stringData|secrets)$
    version: 3.9.4
