apiVersion: v1
data:
    config.yaml: ENC[AES256_GCM,data:JR0D2GQ/d+MxQolci4DdOLMJXyAS6xFyMbqKL9VZZ1HV5HaBpO61mWUaxOTWNHN8Yj22uYeEtaV9GiwlcVtI/OH3flBSSJUm9sO4eGGLgOzQjAx4o1sajXN92+IkJ1nLXhmesG28CqMkn7O7uvHC0iaY//7PBfkpM39RDz3AqE7DydIui/sFfWwEhZciLK47Y5CQZJeLswwKttp/z9xd4KdDKc/CK2pXajgAiFJi9p2Kvq6xgLgco/ANNJ304wSluUP4PEaNvcQZwe8eh8lBfx/s3EHaRUSI8vWk5Javi06YpwuS3Nl/b54H4HKbau2HvDRnLblucR4n0FDMLlGkuBKPS4+ZfbV5jXq3hUFS9A5neKscqiSLC1s9GMvU2NFR60hZN22yw9oWVGjQckQpoU8bahT7vZSGZEFFMxJ6/DXoR+l9nXFTty7TKuksU+G2t1cWU4JjTd3fWAlibOUbssS1gz1TU2uIdL5HrC9qNA6/TNxPwz8XfjUEs5zZWcYNwZQWCERXuSZg3YpbivbhrU1rUkubPzJqcrgLu2tr5NzlyT0MmO+EdncYR64Bk77n6mHY9nL/R9i1D5kMSKUZlpKuY2UKiALBH2pZD4RJ5uBeH6k+hQadWhm6wLjOCaBHMXp7mmiOFchyz2+EvgeamrprGZng0EvSbkiDdPLsZTU=,iv:Ryq4NvtC177oK+tuOl2ccuvE8ajbATUCM/1lydub+5w=,tag:3oOTa00lgfO7C5ruQLvLUA==,type:str]
kind: Secret
metadata:
    name: proxmox-csi-plugin
    namespace: csi-proxmox
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-22T14:40:57Z"
    mac: ENC[AES256_GCM,data:lije82GevpIkxis0gYdSbSqJAY7kDCsAUaFUvnejT/TcbDb+d67pIvcsilqKw8+DwZrPeymcSF1+SG4TUEq8mro31rhGB8enM24PcQYF+Wtr4gQ7r0oUQBnZRvq3KPoi8g7sYvw1SEfm0olvLLTRWRTdsqSdX5Cgjh1AyuPqGiQ=,iv:MjK8qymKjN7aZAUGM6lEExM8dYxJ8eMpg/FTJRSmXdI=,tag:JNK3s0WPW+V7KlWR7Rst0w==,type:str]
    pgp:
        - created_at: "2025-11-22T14:40:57Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwFcjQZ1ckKcARAAm9MhslvvVA5fIOnWDTWkMOylke2+LZUX9kloqf3CfUs0
            571dVsSSFdGQI0M3Hoo5Cm/LCIvMQO6hOuV219rVRHNzjS4HHLa0FD8qCYP9G6kB
            WhNeAswesOJBElYMwC8ht6FEhGLGKLDCMYoZHyDaQydqDVh97p6dhVWlpv+eBv+Q
            Ynpb6S0kQYVWDvcNROGhhJagSsDEeAwzgWOQO8QIFfS0EOi33kIPPslXPWwQHxDC
            j9jUDcTbhvsYlbkX0oEw7TQYhxoPFtNbm4MH5bck4+3iQd90e7yw3SQVj4gRFnie
            WsbADqGr+hN9AVrnUlUQXRhIcFeIVA5lTNFUfquSoRhQHqGDc/pr7d1E/26upYkm
            6nkE4cQhG+McB3kqcQ1/gPPYnPKoridhkbdNWHyiCcpACufkDu9hESAQBl2eYVRh
            uNsfgVlLgc3XJs7tZVKb/kJR7UTD3i/xIiE5OiC9SA8XMGCFbGFbaCwQ3vGIMhXP
            D3nXgL/lZm+tVxTegeMj7Hw37QMeIT9W8e0vpNyeL96aX201ApY+awkTURhKUzOX
            S3PKuR2k4iQLfcBg/MA8Ix9Stt5qDN+J5G3eBtgofcrLODwR6UJ29NMLPsQ5CtO8
            bs2JMrInLtPlJ3eDUi9R5oR272vDufWeAbLLB3xHV8YmtiF3PSAp1pnSrgCoOk7U
            aAEJAhCHBr6W8ug3C6BZIWRFc31ayuyTRS5yKS9cIJLOiAZyuOm1ayKC3ccoB6pL
            ZMzgroqgFdHIBX4GzzoH3T7G65eRCE7ew82/1Qj5rLjNHiHj4QL3eCZrMghWSjnf
            fqpFsoRKBNs3
            =KGAC
            -----END PGP MESSAGE-----
          fp: 4C460A5D1A91A52F3E204754CA746D9D4345890B
    encrypted_regex: ^(data|stringData|secrets)$
    version: 3.9.4
