apiVersion: v1
data:
    config.yaml: ENC[AES256_GCM,data:MrfEY1po4tnMiGozTVdyaUSlScCNG2eWl8VryKHgSvUKNCm0GJTRsoF+puSqjbt6O5+C5aRGoPKLAz0GWihwH07p147+jxFhXEweDmGY8vL2WFyI8dmSgfNb0yN/I8bmuY7QRmR28yHZeB9TvfGSs8igM+4pudINTaH/CsMx2ABmoGrfA6Vl7JTTpgbGTikZPlfNuT44ulvsojlOfPmkm8A/vjTtvKjjVTB1ufUppOyp+3aHiysD+6xHn/nnmMVV/9H0zGBIQI/Bu7DO+gg+J83BDKr8KU3ZZ4OtIeH4aeyZoA9bt6GvQSA3qHl23rV4/T0F/87427dxGQlMJHtcjWIVSHLMg+WAm+MQ/Rtq4B8e2JBoUL9xUfWMeGXWvrkQQcISiuW9n9CQbhQIdYRMwTHx1QMpFOvbdn9u6y0XPPTh71Z/OrXp/T824MKnsaED3Wl7ABanvcJiBeLYBj3M0LeZPBoCgOMe6QSo1RWA1fLqppnOtkttzNjGF/MWbJYIXpBWL67ZL2yUaPXjOIkwhbRhRyWrY+TDEtHsMEvHoBS7LK4dul/ZZ5flON1Y8IM91APiJADgxsSehsxy91wcjaMG+Xc=,iv:NhqKhautvZ7Q3KMep9UnSv0es/xMN0TONTK124W1Vo8=,tag:Wg6C26gHSkQrBTaQ0akZgg==,type:str]
kind: Secret
metadata:
    name: proxmox-csi-plugin
    namespace: proxmox-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-12-07T22:35:48Z"
    mac: ENC[AES256_GCM,data:RLw2wijE5XEaQF7Vb8NuQAHvk36Fc6RRuKlfDCtd2rdaVh7BsUzJUMsVmofzEltk6gNKnDZNhcflo1vRCUkGGQzp9hAnp7EyUcai3dea+dN64fvd6kmcVUGrd9SUvtRLc94KKBxCyqQTApo2UxwcXSW70uVpBYsdLV13luYy9ic=,iv:uXGyD8sJX4NwdFZwr7eOELXRYFU345mrnrSI6e8Zmw4=,tag:D885OQomOSfMz8iESiH/CA==,type:str]
    pgp:
        - created_at: "2025-12-07T22:35:48Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwFcjQZ1ckKcAQ/+KDeJg2ro4B+9CgkDKWodtsfCNFQOVBqqqWRp5oIWnpYw
            zSTce39eVFx5giso5k/cwU+Hg8qC0GI8OISAPbwStWDO2hJPWueQnRk7Zu5nQ7BA
            nNeevsdx3sDkQ5u+e254+i7UWXDS5T3lR17Qy8KafthRD7aH1g4AcAzfQIPyet8/
            rpu4z6cB5sV7SR7x+E7H9rGx/aPMoTVPxVFVJawuv+3gX258FJiDw+KGAq/ItRpc
            NoAsYM8NBHR61IHMaMdnOZ9O9TgY4Y3zqNDbFYxvhudsdCgQdBfbTk9FUs/dQb2T
            xnubfTtgMehUN1n67Ts5skgXGrcUgMAtUqTbuEQD04wMSzW6u2vT97yQ9p3n2Oza
            c8siFUOWvnv4gyum4M8cDKEge8JPa0U6SwBDdFKpyTNEZlgnlMC1iZadU4880kv8
            1LU3bayiXCH86LHGwtgjpG462/siut8c/Tmx6p8OpG0RMRk2xnKTyay1j4syYJsC
            9MEoU5jHhWthaciwE4cyF90sNH4tPs5GvLh3KH3P/HT8l2YEND2ZaeuSxme2+15p
            ADUJacgum0lbpUIUIMv4n3xgqNYkxHxMMClHBXeLQ73xk+2NA78NAheFI1qAHSI+
            2bX8aTpdK/zgXW5HPbKeTxk2CCjpJ6Rw0a5uqxZwTK6SkO8Ei81dmd2cZpjOMgnU
            ZgEJAhBTwXWFki+c6TiD1EHcoHLJfnHLVebK3t2QPd1cj1HRsfPKyEAit86+PrDW
            LlR7hAalHoJ0zLeDPLEYjfG79ohpi/bcSPkoiFkVDV4x6Pt4Y2CcsQ+77JyUSZp8
            xUqdTWsXjA==
            =GodA
            -----END PGP MESSAGE-----
          fp: 4C460A5D1A91A52F3E204754CA746D9D4345890B
    encrypted_regex: ^(data|stringData|secrets)$
    version: 3.9.4
