apiVersion: v1
data:
    alertmanager.yaml: ENC[AES256_GCM,data:Of0MDFkDyo6DNHb6zOUNOsBibSuly9EKK1UZposMlbTViQoTNRGN3WX34K/tRuPh9YqXCpnRuLq07loxSyL3oUP9tBkRocOOHA+a2fSI6M+bBTFJYsx7Ij0GOEAIyIJnJJMb9KhzQMARvqFWOjq+jYIYCoVjJ3X0OhtTkelIuhRLZgeDCVrRe12N0jQvUoWslxM4QXwWgLDWg6WTS9YISllgOKn/x+WJcReaZ0onkDgYkzPkl33YOah+EUwsx3QGghnnbfvgW+bbPEyRH22SHTeK31rp4VTVekNQ21BY5QDBFxFF5+ogRzda6vUliNyTGavEK2Ma0CKBUJ6FifL9limTNOM+lEGXgxQ0WA4YtLMYDqsc3y6ExBlJDALlZPCE9lP5+uhhz9guGRLxbzlVWS0uXOnasN1st80iA5X9CzQc6MF/Ohd4IuWknwwUHGGDnCyUswxojd1/biZ/y/LgkGJtaKEa4HvFdwzR/CneQa6co54Ow2iefr6MUrOvC9whZvnvsjrkgWT3QvHo7F0pcVdlua50KfUxvm1c2sQrIP/ry698WGsZ96M09M0gfw8bniA7kbm7jIqojNdWrCPU81IH1o2P1rO5OPxKTG6oEQav1OBYuOlioHw0WAI3Gp2paxm9WcIrZ5kSrOT012YokyQhdFqGLpsizNkGMIGXhM5JIt25Q/jh56Uvx0O6DM1xrykfig/RdahqtWnq2b0Xa9iKhRrc73JSB3/vZOQOGKKXnF10/U0HnJbBbl9qh5vSYefkaAj8BRYgb705JQ4jEPNJk5cpUxntkxZxvVx22bqJLV+TeUZDFi8stOP6HxA1JfTfEPDU//doM2nE5dNdQQMokkXsI6xHFKfzZOOuk4vUY38u1+zIizE2hCn9Vw3ZgV58A6jlRXWXTZ2MzPJRaEBPQ/S1ZLYggDaA2ezUfWM4kzJQQkvP5e1hea1ivYHenyeYE9ZUs9CcCiAPtq+fqGM6yOY7Rwey09LIViaQkIBA8VNQKontNgp/J7B/YOstHFQqkXLQor9paSLbgLi6/z03Ob+PuKY9U73CWxc1x0jAOaaFH2yb2sWzSqLMdFaIUvir42ZukrDD9LZlKkUK/lS6sKarH5j41PAPA0NdodotcoXt4Psim5UKbkiJUf2LDIIW3cRS0vXOyBnwlX3lSQ7Z+X/utcohHFwHeGICigd2kC4YsbChJOe4qYU1Ibrajqaiz+9RNXUPx3qMtlUxsnUO4Yci4S/NyjBI007sPSLFclw75oqTfDOqAkIFgMND0UMUx9PKf3VH1wBljLPJbBv2YsINqf1Lll5D7ZEO5O/YfVXXxhMKZWPJ14k=,iv:Xr3XDUCN1khGmQEg+TbQm6yOqcKzN3VdYBXhcUmXiZg=,tag:CABemjqIQHvQqLSLnEJQBQ==,type:str]
kind: Secret
metadata:
    name: alertmanager-config
    namespace: observability-system
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-12-08T11:23:49Z"
    mac: ENC[AES256_GCM,data:8ZrVFnkGOvMlj7WjEYdz+UPlNVG3lGrE8Uv7t5yhbEdPtx0f3vnFo+7OD6Q8ZxOsMTowa3M7rJQyV2ydOz7Km5ouTuYGED8YWfakEvTXDoPgGfStXaS0H3cOS6mNUE9MeSub6ydlM6Ze0hb5w5dBkAWo1v1nxmIyfPT6O3mSn/E=,iv:Wp9AHksr/qIcKOyCiLpajAXeFDFgJJj/VJuG/R1o7pU=,tag:BbBAJcQW0KQl9hJZ9yRAgw==,type:str]
    pgp:
        - created_at: "2025-12-08T11:23:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwFcjQZ1ckKcARAAyID1F1SNaZXXqWNOXl4nrg7rfz9zjfpGo1tHaWVw9hfA
            FM2eP8FxVOXRlX/+Oyin8jdF7GWQdemeazSgLcnOgxgHYJBv2pG4w9/toQQQFwy2
            jJqcMVUhRhYzmm2hM+i+Pm50Vp6MT9JWgBU99Cl8dsXXeD/gZ74k+RbexoGv+cNO
            8lpNQ17GDQr3ne374uRPGD3JAhWhYuqAuzl+DYIii/zFY9EA/O1F0grpBLN1iiC/
            94wUw9OAtu3TcvxqTe33llrLTBe1TlmUF20Z3cl3WnM+zmKSwg/EkU0hKbWhI9tr
            mUVso6HwQeJYUmC2LiON7sJ78LUlQck2bu5imWlAcfbgR9gDga8hdb+KMN4GsRWC
            TN3HIPJjVaupg+l1lj8w+HBEo8DKevJYpLa64SwQjukAnHBHbgdVoDpQq0JyVBf+
            mbdNNX4M0+01omC/MO+1S9vucwNN/zcRRc52rLWMqHuPyUKpJgOHQoM3gV6knYe/
            WVZdFgNN3z9ier496fPa+DnNAbC7wasYuXPRQ8F1aBCMoW+5RHDxfdl6lJfd/eMC
            f5hHiUlJKgYWl+ksHrS5oYADmOu367rORApuGDjZcfW1+u9ePuo8hZb9MeT73bcr
            RjynVrc4zbdbIgI7FqpUZ7s7+tGH1FgzRXxqQRcMJIc3p+TLmZZjATACT+3N69TU
            aAEJAhCZBr72L/3bLko+ovDPyd7laxaXO4dQo+hmqPKvCEAxc8Ts7n7ueEwGakGs
            2hWx0QEKRAA7atz/MOc4LohT+ICznjC+i3gvPmvXAx8rcLgdsjyXzbmwJoUSGEjn
            9T15IL2V3fJy
            =l/NF
            -----END PGP MESSAGE-----
          fp: 4C460A5D1A91A52F3E204754CA746D9D4345890B
    encrypted_regex: ^(data|stringData|secrets)$
    version: 3.9.4
