apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app.yaml
  - issuer-selfsigned.yaml
  - ca-certificate.yaml
  - ca-issuer.yaml
  - vault-server-certificate.yaml
  - vault-injector-certificate.yaml
  - terraform/
patches:
  - target:
      kind: Application
      name: vault
    path: ../../../common/patches/argocd-app-settings.yaml
