apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - storageclass.yaml
  - volumeattributesclass.yaml
  # - volumesnapshotclass.yaml  # Not supported by Proxmox CSI driver yet