apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../apps/operators/scheduling/loft/vcluster/
  - ../../../a01-vcluster/config/

namePrefix: "a01-"

patches:
  - target:
      kind: Application
      name: vcluster
    path: patches/vcluster.yaml
