apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../apps/operators/scheduling/loft/vcluster/

namePrefix: "a01-"

patches:
  - target:
      kind: Application
      name: vcluster
    path: patches/vcluster.yaml

