apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:

  - ../../../operators/gitops/argocd/alternative/
  - ../../../operators/security/teleport-kube-agent
  - ../../../operators/observability/metrics-server