apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Install CSI snapshot CRDs and controller from official release
  - https://github.com/kubernetes-csi/external-snapshotter/deploy/kubernetes/snapshot-controller?ref=v8.2.0
  - https://github.com/kubernetes-csi/external-snapshotter/client/config/crd?ref=v8.2.0
