apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    # Must Run in Kube-System
    namespace: observability-system
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 80.2.2
    chart: kube-prometheus-stack
    helm:
      valuesObject:
        # NOTE: These must be set manually to the control plane IP addresses
        kubeEtcd:
          # endpoints:
          #   - "{{ .cluster.etcdEndpoints.cpAddress1 }}"
          #   - "{{ .cluster.etcdEndpoints.cpAddress2 }}"
          #   - "{{ .cluster.etcdEndpoints.cpAddress3 }}"
          service:
            enabled: true
            ipFamilyPolicy: SingleStack
            ipFamilies:
              - IPv4
            port: 2379
            targetPort: 2379
          serviceMonitor:
            scheme: https
            insecureSkipVerify: true
            caFile: /etc/prometheus/secrets/etcd-certs/etcd-ca.crt
            certFile: /etc/prometheus/secrets/etcd-certs/etcd-client.crt
            keyFile: /etc/prometheus/secrets/etcd-certs/etcd-client-key.key
        kubeControllerManager:
          service:
            selector:
              k8s-app: kube-controller-manager
        kubeScheduler:
          service:
            selector:
              k8s-app: kube-scheduler
        alertmanager:
          alertmanagerSpec:
            forceEnableClusterMode: true
            useExistingSecret: true
            secrets:
              - alertmanager-config
            configSecret: alertmanager-config
            storage:
              volumeClaimTemplate:
                spec:
                  storageClassName: proxmox
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: 10Gi
        prometheus:
          prometheusSpec:
            secrets:
              - etcd-certs
            retention: 30d
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: "{{ .cluster.settings.defaultStorageClass }}"
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: 150Gi
        grafana:
          grafana.ini:
            auth:
              disable_login_form: true
              disable_signout_menu: true
            # auth.basic:
            #   enabled: true
            auth.anonymous:
              enabled: true
              org_name: "Main Org."
              org_role: Admin