apiVersion: v1
kind: Secret
metadata:
    name: etcd-certs
    namespace: observability-system
type: Opaque
stringData:
  etcd-ca.crt: |
  "{{ .ejson.etcd.caCert | indent 4 }}"
  etcd-client.crt: |
  "{{ .ejson.etcd.serverCert | indent 4 }}"
  etcd-client-key.key: |
  "{{ .ejson.etcd.serverKey | indent 4 }}"