apiVersion: v1
kind: Secret
metadata:
    name: etcd-certs
    namespace: observability-system
type: Opaque
stringData:
  etcd-ca.crt: |-
    {{ .ejson.etcd.caCert | strings.Indent "    " }}
  etcd-client.crt: |-
    {{ .ejson.etcd.serverCert | strings.Indent "    " }}
  etcd-client-key.key: |-
    {{ .ejson.etcd.serverKey | strings.Indent "    " }}