apiVersion: apps/v1
kind: Deployment
metadata:
  name: goritch
  namespace: growth-vat
  labels:
    test: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goritch
  template:
    metadata:
      labels:
        app: goritch
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      initContainers:
        - name: write-no-ghoritch
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - |
              cat <<'EOF' > /no-ghoritch/index.html
              <html>
                <head>
                  <title>Cheese</title>
                </head>
                <body>
                  <pre>
                    The Rat is gone. 
                  </pre>
                </body>
              </html>
              EOF
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: no-ghoritch-page
              mountPath: /no-ghoritch
      containers:
        - name: warp-stone
          image: nginxinc/nginx-unprivileged:latest
          volumeMounts:
            - name: index-html
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
            - name: no-ghoritch-page
              mountPath: /usr/share/nginx/html/no-ghoritch
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
      volumes:
        - name: index-html
          configMap:
            name: page-content
        - name: no-ghoritch-page
          persistentVolumeClaim:
            claimName: no-ghoritch-page