apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - csi-proxmox/proxmox-token.yaml
  - teleport-kube-agent/teleport-join-token.yaml
  - kube-prometheus-stack/etcd-certs.yaml
  - kube-prometheus-stack/alertmanager-config.yaml