apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patch
spec:
  source:
    helm:
      valuesObject:
        kubeClusterName: kubelize-core
        apps:
          - name: core-pve
            uri: https://10.130.5.10:8006
            insecure_skip_verify: true
          - name: core-grafana
            uri: http://kube-prometheus-stack-grafana.observability-system.svc.cluster.local
            rewrite:
              headers:
                - "Host: core-grafana.teleport.kubelize.com"
                - "csrf_trusted_origins: 'http://core-grafana.teleport.kubelize.com'"
          - name: core-prometheus
            uri: http://kube-prometheus-stack-prometheus.observability-system.svc.cluster.local:9090
          - name: core-alertmanager
            uri: http://alertmanager-operated.observability-system.svc.cluster.local:9093
          - name: core-argocd
            uri: http://argocd-server.argocd.svc.cluster.local
          - name: core-hubble
            uri: http://hubble-ui.kube-system.svc.cluster.local
          - name: vault-test
            uri: https://vault-active.vault-test.svc.cluster.local:8200
